<?xml version="1.0"?>
<package format="3">
  <name>realsense_cv_pipe</name>
  <version>0.0.1</version>
  <description>Composable rectification + extra node for Realsense.</description>

  <maintainer email="calvin.rubens@indrorobotics.com">Calvin-InDro</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>isaac_ros_image_proc</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>