<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>px4_state_machine</name>
  <version>0.0.1</version>
  <description>ROS2 PX4 Cypher State Machine</description>
  <maintainer email="calvin.rubens@indrorobotics.com">Calvin-InDro</maintainer>
  <license>BSD-3</license>

  <depend>rclpy</depend>
  <depend>px4_msgs</depend>
  <depend>px4_vslam</depend>
  <depend>px4_ros2_cpp</depend>
  <depend>geometry_msgs</depend>
  <depend>state_machine_interfaces</depend>

  <depend>isaac_ros_visual_slam_interfaces</depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <buildtool_depend>ament_python</buildtool_depend>

   <export>
    <build_type>ament_python</build_type>
  </export>
</package>


