<?xml version="1.0"?>
<package format="3">
  <name>gst_camera_info</name>
  <version>0.0.1</version>
  <description>Package for launching Jetson CSI pipelines and publishing associated camera information</description>
  <maintainer email="calvin.rubens@indrorobotics.com">Calvin Rubens</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
