<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>px4_vslam_reactor</name>
  <version>0.0.1</version>
  <description>ISAAC ROS VSLAM corrective ROS2 package</description>
  <maintainer email="calvin.rubens@indrorobotics.com">Calvin Rubens</maintainer>
  <license>Apache License 2.0</license>

  <depend>rclpy</depend>
  <depend>tf2_ros</depend>
  <depend>px4_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>px4_vslam</depend>
  <depend>sensor_msgs</depend>
  <depend>px4_ros2_cpp</depend>
  <depend>geometry_msgs</depend>
  <depend>message_filters</depend>
  <depend>isaac_ros_visual_slam</depend>
  <depend>arid_drone_description</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
