<?xml version="1.0"?>
<package format="3">
  <name>cypher_argus</name>
  <version>0.0.1</version>
  <description>Argus camera + rectification + mono conversion with calibration-based frame_id</description>

  <maintainer email="calvin.rubens@indrorobotics.com">Calvin Rubens</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>isaac_ros_argus_camera</exec_depend>
  <exec_depend>isaac_ros_image_proc</exec_depend>

  <exec_depend>ament_index_cpp</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>