<?xml version="1.0"?>
<package format="3">
  <name>gst_cam_node</name>
  <version>0.0.1</version>
  <description>ROS2 C++ node for launching GStreamer camera pipeline</description>

  <maintainer email="calvin.rubens@indrorobotics.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>ament_index_cpp</build_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>ament_index_cpp</exec_depend>

  <depend>libgstreamer1.0-dev</depend>
  <depend>libgstreamer-plugins-base1.0-dev</depend>
  <depend>camera_info_manager</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
