<package format="3">
  <name>state_machine_interfaces</name>
  <version>0.0.1</version>
  <description>Custom services for PX4 State Machine</description>
  <maintainer email="calvin.rubens@indrorobotics.com">Calvin-InDro</maintainer>
  <license>BSD-3</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rosidl_default_generators</depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
